config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :posts

  root 'static_pages#show', page: 'home'
  get '/:page', to: 'static_pages#show', as: 'static_pages'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :title, :message
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, format: { with: /[a-z]|_/,
                                                 message: 'only allows lowercase letters and underscores' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :access_denied
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from ActionController::RoutingError, with: :not_found
  rescue_from AbstractController::ActionNotFound, with: :not_found
  rescue_from ActionController::ParameterMissing, with: :request_invalid

  def access_denied(_exception)
    redirect_to static_pages_url(page: 'access-denied')
  end

  def not_found(_exception)
    redirect_to static_pages_url(page: 'not-found-404')
  end

  def request_invalid(_exception)
    redirect_to static_pages_url(page: 'request-invalid')
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @posts = Post.all
    @user_names = User.all.map { |user| user.nickname }
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_url(@post)
    else
      redirect_to posts_url
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post, :change?
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      redirect_to edit_post_url
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post, :change?
    if @post.destroy
      redirect_to posts_url
    else
      redirect_to post_url(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :message
    )
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  STATIC_PAGES = {
    'home': 'home',
    'not-found-404': 'not_found_404',
    'access-denied': 'access_denied',
    'request-invalid': 'request_invalid'
  }.freeze

  def show
    if STATIC_PAGES[params[:page].to_sym].nil?
      render (STATIC_PAGES['not-found-404'.to_sym]).to_s
    else
      render (STATIC_PAGES[params[:page].to_sym]).to_s
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user, event: :authentication
      redirect_to root_url, notice: 'Sign up successfull'    
    else
      redirect_to root_url, alert: 'Sign up failed'
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation
    )
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag '_header' %>

<div class="header__wrapper">
  <div class="header__panel">
    <%= image_tag 'logo.png', class: "header__logo-wrapper" %>
    <div class="header__sections-wrapper">
      <%= link_to 'Posts', posts_url, class: "header__sections-item" %>
    </div>
  </div>
  <div class="header__buttons-wrapper ">
    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_url, method: :delete, class: "link-button" %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_url, class: "link-button" %>
      <%= link_to 'Sign in', new_user_session_url, class: "link-button" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Masterpiece</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag '_global' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= form_with(model: @post, method: 'patch') do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :message %>
  <%= f.text_area :message, size: "60x10" %>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<div class="posts posts__title-wrapper">
  <div class="posts posts__title">All posts</div>
  <%= link_to "New", new_post_url, class: "link-button" %>
</div>
<div class="posts posts__wrapper">
  <% @posts.each do |post| %>
    <%= link_to post_url(post), class: "posts posts__card" do %>
      <div class="card card__title-wrapper">
        <div class="card card__title">
          <div class="card card__text">
            <%= post.title %>
          </div>
        </div>
        <div class="card card__author">
          <div class="card card__text">
            <%= @user_names[post.user_id] %>
          </div>
        </div>
      </div>
      <div class="card card__body">
        <div class="card card__text">
          <%= post.message %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if @posts.empty? %>
    Empty
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= form_with(model: @post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :message %>
  <%= f.text_area :message, size: "60x10" %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="posts posts__title-wrapper">
  <div class="posts posts__title">Post info</div>
  <%= link_to "Edit", edit_post_url(@post), class: "link-button" %>
  <%= link_to "Delete", post_url(@post), method: :delete, class: "link-button" %>
</div>


<div class="card card__title-wrapper">
  <div class="card card__title">
    <div class="card card__text">
      <%= @post.title %>
    </div>
  </div>
  <div class="card card__author">
    <div class="card card__text">
      <%= @user.nickname %>
    </div>
  </div>
</div>
<div class="card card__body">
  <div class="card card__text">
    <%= @post.message %>
  </div>
</div>

app/views/static_pages/access_denied.html.erb
<h1>You are not authorized to do this</h1>

app/views/static_pages/home.html.erb
<h1>Home</h1>

app/views/static_pages/not_found_404.html.erb
<h1>Not found</h1>

app/views/static_pages/request_invalid.html.erb
<h1>Request invalid</h1>
<h3>Maybe typo in some param's name?</h3>